/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChannelProfile {
  'id' : string,
  'channelType' : ChannelType,
  'name' : string,
  'urlOrHandle' : string,
  'notes' : [] | [string],
}
export type ChannelType = { 'instagram' : null } |
  { 'whatsapp' : null } |
  { 'website' : null } |
  { 'phone' : null } |
  { 'telegram' : null };
export interface ContentPlan {
  'id' : string,
  'status' : { 'published' : null } |
    { 'planned' : null } |
    { 'draft' : null },
  'title' : string,
  'contentType' : ContentType,
  'scheduledDate' : [] | [Time],
  'channel' : ChannelType,
}
export type ContentType = { 'post' : null } |
  { 'reel' : null } |
  { 'article' : null } |
  { 'story' : null };
export interface ExportData {
  'tasks' : Array<Task>,
  'channels' : Array<ChannelProfile>,
  'workItems' : Array<WorkInboxItem>,
  'notes' : Array<Note>,
  'contentPlans' : Array<ContentPlan>,
}
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'lastUpdated' : [] | [Time],
}
export interface Task {
  'id' : string,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'priority' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkInboxItem {
  'id' : string,
  'status' : WorkItemStatus,
  'source' : ChannelType,
  'createdAt' : Time,
  'dueDate' : [] | [Time],
  'description' : string,
}
export type WorkItemStatus = { 'new' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChannelProfile' : ActorMethod<[ChannelProfile], undefined>,
  'addContentPlan' : ActorMethod<[ContentPlan], undefined>,
  'addNote' : ActorMethod<[Note], undefined>,
  'addTask' : ActorMethod<[Task], undefined>,
  'addWorkInboxItem' : ActorMethod<[WorkInboxItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChannelProfile' : ActorMethod<[string], undefined>,
  'deleteContentPlan' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'deleteWorkInboxItem' : ActorMethod<[string], undefined>,
  'exportUserData' : ActorMethod<[], ExportData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelProfiles' : ActorMethod<[], Array<ChannelProfile>>,
  'getContentPlans' : ActorMethod<[], Array<ContentPlan>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTodayTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkInboxItems' : ActorMethod<[], Array<WorkInboxItem>>,
  'importUserData' : ActorMethod<[ExportData], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChannelProfile' : ActorMethod<[ChannelProfile], undefined>,
  'updateContentPlan' : ActorMethod<[ContentPlan], undefined>,
  'updateNote' : ActorMethod<[Note], undefined>,
  'updateTask' : ActorMethod<[Task], undefined>,
  'updateWorkInboxItem' : ActorMethod<[WorkInboxItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];