/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChannelType = IDL.Variant({
  'instagram' : IDL.Null,
  'whatsapp' : IDL.Null,
  'website' : IDL.Null,
  'phone' : IDL.Null,
  'telegram' : IDL.Null,
});
export const ChannelProfile = IDL.Record({
  'id' : IDL.Text,
  'channelType' : ChannelType,
  'name' : IDL.Text,
  'urlOrHandle' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const ContentType = IDL.Variant({
  'post' : IDL.Null,
  'reel' : IDL.Null,
  'article' : IDL.Null,
  'story' : IDL.Null,
});
export const Time = IDL.Int;
export const ContentPlan = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'published' : IDL.Null,
    'planned' : IDL.Null,
    'draft' : IDL.Null,
  }),
  'title' : IDL.Text,
  'contentType' : ContentType,
  'scheduledDate' : IDL.Opt(Time),
  'channel' : ChannelType,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'lastUpdated' : IDL.Opt(Time),
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'priority' : IDL.Nat,
});
export const WorkItemStatus = IDL.Variant({
  'new' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const WorkInboxItem = IDL.Record({
  'id' : IDL.Text,
  'status' : WorkItemStatus,
  'source' : ChannelType,
  'createdAt' : Time,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'owner' : IDL.Principal,
  'size' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'fileName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'uploadedAt' : Time,
});
export const ExportData = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'channels' : IDL.Vec(ChannelProfile),
  'workItems' : IDL.Vec(WorkInboxItem),
  'fileMetadata' : IDL.Vec(FileMetadata),
  'notes' : IDL.Vec(Note),
  'contentPlans' : IDL.Vec(ContentPlan),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChannelProfile' : IDL.Func([ChannelProfile], [], []),
  'addContentPlan' : IDL.Func([ContentPlan], [], []),
  'addNote' : IDL.Func([Note], [], []),
  'addTask' : IDL.Func([Task], [], []),
  'addWorkInboxItem' : IDL.Func([WorkInboxItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFileMetadata' : IDL.Func([FileMetadata], [], []),
  'deleteChannelProfile' : IDL.Func([IDL.Text], [], []),
  'deleteContentPlan' : IDL.Func([IDL.Text], [], []),
  'deleteFileMetadata' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'deleteWorkInboxItem' : IDL.Func([IDL.Text], [], []),
  'exportUserData' : IDL.Func([], [ExportData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelProfiles' : IDL.Func([], [IDL.Vec(ChannelProfile)], ['query']),
  'getContentPlans' : IDL.Func([], [IDL.Vec(ContentPlan)], ['query']),
  'getFileMetadata' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTodayTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkInboxItems' : IDL.Func([], [IDL.Vec(WorkInboxItem)], ['query']),
  'importUserData' : IDL.Func([ExportData], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileMetadata' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChannelProfile' : IDL.Func([ChannelProfile], [], []),
  'updateContentPlan' : IDL.Func([ContentPlan], [], []),
  'updateFileMetadata' : IDL.Func([IDL.Text, FileMetadata], [], []),
  'updateNote' : IDL.Func([Note], [], []),
  'updateTask' : IDL.Func([Task], [], []),
  'updateWorkInboxItem' : IDL.Func([WorkInboxItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChannelType = IDL.Variant({
    'instagram' : IDL.Null,
    'whatsapp' : IDL.Null,
    'website' : IDL.Null,
    'phone' : IDL.Null,
    'telegram' : IDL.Null,
  });
  const ChannelProfile = IDL.Record({
    'id' : IDL.Text,
    'channelType' : ChannelType,
    'name' : IDL.Text,
    'urlOrHandle' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const ContentType = IDL.Variant({
    'post' : IDL.Null,
    'reel' : IDL.Null,
    'article' : IDL.Null,
    'story' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContentPlan = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'published' : IDL.Null,
      'planned' : IDL.Null,
      'draft' : IDL.Null,
    }),
    'title' : IDL.Text,
    'contentType' : ContentType,
    'scheduledDate' : IDL.Opt(Time),
    'channel' : ChannelType,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'lastUpdated' : IDL.Opt(Time),
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'priority' : IDL.Nat,
  });
  const WorkItemStatus = IDL.Variant({
    'new' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const WorkInboxItem = IDL.Record({
    'id' : IDL.Text,
    'status' : WorkItemStatus,
    'source' : ChannelType,
    'createdAt' : Time,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'owner' : IDL.Principal,
    'size' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'fileName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'uploadedAt' : Time,
  });
  const ExportData = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'channels' : IDL.Vec(ChannelProfile),
    'workItems' : IDL.Vec(WorkInboxItem),
    'fileMetadata' : IDL.Vec(FileMetadata),
    'notes' : IDL.Vec(Note),
    'contentPlans' : IDL.Vec(ContentPlan),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChannelProfile' : IDL.Func([ChannelProfile], [], []),
    'addContentPlan' : IDL.Func([ContentPlan], [], []),
    'addNote' : IDL.Func([Note], [], []),
    'addTask' : IDL.Func([Task], [], []),
    'addWorkInboxItem' : IDL.Func([WorkInboxItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFileMetadata' : IDL.Func([FileMetadata], [], []),
    'deleteChannelProfile' : IDL.Func([IDL.Text], [], []),
    'deleteContentPlan' : IDL.Func([IDL.Text], [], []),
    'deleteFileMetadata' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'deleteWorkInboxItem' : IDL.Func([IDL.Text], [], []),
    'exportUserData' : IDL.Func([], [ExportData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelProfiles' : IDL.Func([], [IDL.Vec(ChannelProfile)], ['query']),
    'getContentPlans' : IDL.Func([], [IDL.Vec(ContentPlan)], ['query']),
    'getFileMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileMetadata)],
        ['query'],
      ),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTodayTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkInboxItems' : IDL.Func([], [IDL.Vec(WorkInboxItem)], ['query']),
    'importUserData' : IDL.Func([ExportData], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileMetadata' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChannelProfile' : IDL.Func([ChannelProfile], [], []),
    'updateContentPlan' : IDL.Func([ContentPlan], [], []),
    'updateFileMetadata' : IDL.Func([IDL.Text, FileMetadata], [], []),
    'updateNote' : IDL.Func([Note], [], []),
    'updateTask' : IDL.Func([Task], [], []),
    'updateWorkInboxItem' : IDL.Func([WorkInboxItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };