/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExportData {
    tasks: Array<Task>;
    channels: Array<ChannelProfile>;
    workItems: Array<WorkInboxItem>;
    notes: Array<Note>;
    contentPlans: Array<ContentPlan>;
}
export type Time = bigint;
export interface ContentPlan {
    id: string;
    status: Variant_published_planned_draft;
    title: string;
    contentType: ContentType;
    scheduledDate?: Time;
    channel: ChannelType;
}
export interface ChannelProfile {
    id: string;
    channelType: ChannelType;
    name: string;
    urlOrHandle: string;
    notes?: string;
}
export interface Task {
    id: string;
    title: string;
    completed: boolean;
    dueDate?: Time;
    priority: bigint;
}
export interface WorkInboxItem {
    id: string;
    status: WorkItemStatus;
    source: ChannelType;
    createdAt: Time;
    dueDate?: Time;
    description: string;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
    email?: string;
}
export interface Note {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    lastUpdated?: Time;
}
export enum ChannelType {
    instagram = "instagram",
    whatsapp = "whatsapp",
    website = "website",
    phone = "phone",
    telegram = "telegram"
}
export enum ContentType {
    post = "post",
    reel = "reel",
    article = "article",
    story = "story"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_published_planned_draft {
    published = "published",
    planned = "planned",
    draft = "draft"
}
export enum WorkItemStatus {
    new_ = "new",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChannelProfile(profile: ChannelProfile): Promise<void>;
    addContentPlan(plan: ContentPlan): Promise<void>;
    addNote(note: Note): Promise<void>;
    addTask(task: Task): Promise<void>;
    addWorkInboxItem(item: WorkInboxItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteChannelProfile(profileId: string): Promise<void>;
    deleteContentPlan(planId: string): Promise<void>;
    deleteNote(noteId: string): Promise<void>;
    deleteTask(taskId: string): Promise<void>;
    deleteWorkInboxItem(itemId: string): Promise<void>;
    exportUserData(): Promise<ExportData>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannelProfiles(): Promise<Array<ChannelProfile>>;
    getContentPlans(): Promise<Array<ContentPlan>>;
    getNotes(): Promise<Array<Note>>;
    getTasks(): Promise<Array<Task>>;
    getTodayTasks(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkInboxItems(): Promise<Array<WorkInboxItem>>;
    importUserData(data: ExportData): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateChannelProfile(updatedProfile: ChannelProfile): Promise<void>;
    updateContentPlan(updatedPlan: ContentPlan): Promise<void>;
    updateNote(updatedNote: Note): Promise<void>;
    updateTask(updatedTask: Task): Promise<void>;
    updateWorkInboxItem(updatedItem: WorkInboxItem): Promise<void>;
}
import type { ChannelProfile as _ChannelProfile, ChannelType as _ChannelType, ContentPlan as _ContentPlan, ContentType as _ContentType, ExportData as _ExportData, Note as _Note, Task as _Task, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkInboxItem as _WorkInboxItem, WorkItemStatus as _WorkItemStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChannelProfile(arg0: ChannelProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChannelProfile(to_candid_ChannelProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChannelProfile(to_candid_ChannelProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addContentPlan(arg0: ContentPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContentPlan(to_candid_ContentPlan_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContentPlan(to_candid_ContentPlan_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNote(arg0: Note): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(to_candid_Note_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(to_candid_Note_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(to_candid_Task_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(to_candid_Task_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWorkInboxItem(arg0: WorkInboxItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkInboxItem(to_candid_WorkInboxItem_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkInboxItem(to_candid_WorkInboxItem_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteChannelProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannelProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannelProfile(arg0);
            return result;
        }
    }
    async deleteContentPlan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentPlan(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteWorkInboxItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkInboxItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkInboxItem(arg0);
            return result;
        }
    }
    async exportUserData(): Promise<ExportData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportUserData();
                return from_candid_ExportData_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportUserData();
            return from_candid_ExportData_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelProfiles(): Promise<Array<ChannelProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelProfiles();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelProfiles();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentPlans(): Promise<Array<ContentPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentPlans();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentPlans();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayTasks();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayTasks();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkInboxItems(): Promise<Array<WorkInboxItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkInboxItems();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkInboxItems();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async importUserData(arg0: ExportData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importUserData(to_candid_ExportData_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importUserData(to_candid_ExportData_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateChannelProfile(arg0: ChannelProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannelProfile(to_candid_ChannelProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannelProfile(to_candid_ChannelProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateContentPlan(arg0: ContentPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentPlan(to_candid_ContentPlan_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentPlan(to_candid_ContentPlan_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNote(arg0: Note): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(to_candid_Note_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(to_candid_Note_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(to_candid_Task_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(to_candid_Task_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateWorkInboxItem(arg0: WorkInboxItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkInboxItem(to_candid_WorkInboxItem_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkInboxItem(to_candid_WorkInboxItem_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ChannelProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChannelProfile): ChannelProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ChannelType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChannelType): ChannelType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ContentPlan_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentPlan): ContentPlan {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_ExportData_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportData): ExportData {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_WorkInboxItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkInboxItem): WorkInboxItem {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WorkItemStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkItemStatus): WorkItemStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_Task>;
    channels: Array<_ChannelProfile>;
    workItems: Array<_WorkInboxItem>;
    notes: Array<_Note>;
    contentPlans: Array<_ContentPlan>;
}): {
    tasks: Array<Task>;
    channels: Array<ChannelProfile>;
    workItems: Array<WorkInboxItem>;
    notes: Array<Note>;
    contentPlans: Array<ContentPlan>;
} {
    return {
        tasks: from_candid_vec_n22(_uploadFile, _downloadFile, value.tasks),
        channels: from_candid_vec_n26(_uploadFile, _downloadFile, value.channels),
        workItems: from_candid_vec_n32(_uploadFile, _downloadFile, value.workItems),
        notes: from_candid_vec_n37(_uploadFile, _downloadFile, value.notes),
        contentPlans: from_candid_vec_n40(_uploadFile, _downloadFile, value.contentPlans)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    completed: boolean;
    dueDate: [] | [_Time];
    priority: bigint;
}): {
    id: string;
    title: string;
    completed: boolean;
    dueDate?: Time;
    priority: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.dueDate)),
        priority: value.priority
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    channelType: _ChannelType;
    name: string;
    urlOrHandle: string;
    notes: [] | [string];
}): {
    id: string;
    channelType: ChannelType;
    name: string;
    urlOrHandle: string;
    notes?: string;
} {
    return {
        id: value.id,
        channelType: from_candid_ChannelType_n29(_uploadFile, _downloadFile, value.channelType),
        name: value.name,
        urlOrHandle: value.urlOrHandle,
        notes: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WorkItemStatus;
    source: _ChannelType;
    createdAt: _Time;
    dueDate: [] | [_Time];
    description: string;
}): {
    id: string;
    status: WorkItemStatus;
    source: ChannelType;
    createdAt: Time;
    dueDate?: Time;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_WorkItemStatus_n35(_uploadFile, _downloadFile, value.status),
        source: from_candid_ChannelType_n29(_uploadFile, _downloadFile, value.source),
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    createdAt: _Time;
    lastUpdated: [] | [_Time];
}): {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    lastUpdated?: Time;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        lastUpdated: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.lastUpdated))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        published: null;
    } | {
        planned: null;
    } | {
        draft: null;
    };
    title: string;
    contentType: _ContentType;
    scheduledDate: [] | [_Time];
    channel: _ChannelType;
}): {
    id: string;
    status: Variant_published_planned_draft;
    title: string;
    contentType: ContentType;
    scheduledDate?: Time;
    channel: ChannelType;
} {
    return {
        id: value.id,
        status: from_candid_variant_n43(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contentType: from_candid_ContentType_n44(_uploadFile, _downloadFile, value.contentType),
        scheduledDate: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.scheduledDate)),
        channel: from_candid_ChannelType_n29(_uploadFile, _downloadFile, value.channel)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Time;
    email: [] | [string];
}): {
    name: string;
    createdAt: Time;
    email?: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    instagram: null;
} | {
    whatsapp: null;
} | {
    website: null;
} | {
    phone: null;
} | {
    telegram: null;
}): ChannelType {
    return "instagram" in value ? ChannelType.instagram : "whatsapp" in value ? ChannelType.whatsapp : "website" in value ? ChannelType.website : "phone" in value ? ChannelType.phone : "telegram" in value ? ChannelType.telegram : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): WorkItemStatus {
    return "new" in value ? WorkItemStatus.new : "completed" in value ? WorkItemStatus.completed : "inProgress" in value ? WorkItemStatus.inProgress : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    planned: null;
} | {
    draft: null;
}): Variant_published_planned_draft {
    return "published" in value ? Variant_published_planned_draft.published : "planned" in value ? Variant_published_planned_draft.planned : "draft" in value ? Variant_published_planned_draft.draft : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    post: null;
} | {
    reel: null;
} | {
    article: null;
} | {
    story: null;
}): ContentType {
    return "post" in value ? ContentType.post : "reel" in value ? ContentType.reel : "article" in value ? ContentType.article : "story" in value ? ContentType.story : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChannelProfile>): Array<ChannelProfile> {
    return value.map((x)=>from_candid_ChannelProfile_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkInboxItem>): Array<WorkInboxItem> {
    return value.map((x)=>from_candid_WorkInboxItem_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentPlan>): Array<ContentPlan> {
    return value.map((x)=>from_candid_ContentPlan_n41(_uploadFile, _downloadFile, x));
}
function to_candid_ChannelProfile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChannelProfile): _ChannelProfile {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ChannelType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChannelType): _ChannelType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ContentPlan_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentPlan): _ContentPlan {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ContentType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ExportData_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExportData): _ExportData {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Note_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Note): _Note {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_WorkInboxItem_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkInboxItem): _WorkInboxItem {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_WorkItemStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkItemStatus): _WorkItemStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    lastUpdated?: Time;
}): {
    id: string;
    title: string;
    content: string;
    createdAt: _Time;
    lastUpdated: [] | [_Time];
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated ? candid_some(value.lastUpdated) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    completed: boolean;
    dueDate?: Time;
    priority: bigint;
}): {
    id: string;
    title: string;
    completed: boolean;
    dueDate: [] | [_Time];
    priority: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        priority: value.priority
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: WorkItemStatus;
    source: ChannelType;
    createdAt: Time;
    dueDate?: Time;
    description: string;
}): {
    id: string;
    status: _WorkItemStatus;
    source: _ChannelType;
    createdAt: _Time;
    dueDate: [] | [_Time];
    description: string;
} {
    return {
        id: value.id,
        status: to_candid_WorkItemStatus_n16(_uploadFile, _downloadFile, value.status),
        source: to_candid_ChannelType_n3(_uploadFile, _downloadFile, value.source),
        createdAt: value.createdAt,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    channelType: ChannelType;
    name: string;
    urlOrHandle: string;
    notes?: string;
}): {
    id: string;
    channelType: _ChannelType;
    name: string;
    urlOrHandle: string;
    notes: [] | [string];
} {
    return {
        id: value.id,
        channelType: to_candid_ChannelType_n3(_uploadFile, _downloadFile, value.channelType),
        name: value.name,
        urlOrHandle: value.urlOrHandle,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<Task>;
    channels: Array<ChannelProfile>;
    workItems: Array<WorkInboxItem>;
    notes: Array<Note>;
    contentPlans: Array<ContentPlan>;
}): {
    tasks: Array<_Task>;
    channels: Array<_ChannelProfile>;
    workItems: Array<_WorkInboxItem>;
    notes: Array<_Note>;
    contentPlans: Array<_ContentPlan>;
} {
    return {
        tasks: to_candid_vec_n53(_uploadFile, _downloadFile, value.tasks),
        channels: to_candid_vec_n54(_uploadFile, _downloadFile, value.channels),
        workItems: to_candid_vec_n55(_uploadFile, _downloadFile, value.workItems),
        notes: to_candid_vec_n56(_uploadFile, _downloadFile, value.notes),
        contentPlans: to_candid_vec_n57(_uploadFile, _downloadFile, value.contentPlans)
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Time;
    email?: string;
}): {
    name: string;
    createdAt: _Time;
    email: [] | [string];
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_published_planned_draft;
    title: string;
    contentType: ContentType;
    scheduledDate?: Time;
    channel: ChannelType;
}): {
    id: string;
    status: {
        published: null;
    } | {
        planned: null;
    } | {
        draft: null;
    };
    title: string;
    contentType: _ContentType;
    scheduledDate: [] | [_Time];
    channel: _ChannelType;
} {
    return {
        id: value.id,
        status: to_candid_variant_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contentType: to_candid_ContentType_n8(_uploadFile, _downloadFile, value.contentType),
        scheduledDate: value.scheduledDate ? candid_some(value.scheduledDate) : candid_none(),
        channel: to_candid_ChannelType_n3(_uploadFile, _downloadFile, value.channel)
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkItemStatus): {
    new: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == WorkItemStatus.new ? {
        new_: null
    } : value == WorkItemStatus.completed ? {
        completed: null
    } : value == WorkItemStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChannelType): {
    instagram: null;
} | {
    whatsapp: null;
} | {
    website: null;
} | {
    phone: null;
} | {
    telegram: null;
} {
    return value == ChannelType.instagram ? {
        instagram: null
    } : value == ChannelType.whatsapp ? {
        whatsapp: null
    } : value == ChannelType.website ? {
        website: null
    } : value == ChannelType.phone ? {
        phone: null
    } : value == ChannelType.telegram ? {
        telegram: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_published_planned_draft): {
    published: null;
} | {
    planned: null;
} | {
    draft: null;
} {
    return value == Variant_published_planned_draft.published ? {
        published: null
    } : value == Variant_published_planned_draft.planned ? {
        planned: null
    } : value == Variant_published_planned_draft.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    post: null;
} | {
    reel: null;
} | {
    article: null;
} | {
    story: null;
} {
    return value == ContentType.post ? {
        post: null
    } : value == ContentType.reel ? {
        reel: null
    } : value == ContentType.article ? {
        article: null
    } : value == ContentType.story ? {
        story: null
    } : value;
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Task>): Array<_Task> {
    return value.map((x)=>to_candid_Task_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ChannelProfile>): Array<_ChannelProfile> {
    return value.map((x)=>to_candid_ChannelProfile_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkInboxItem>): Array<_WorkInboxItem> {
    return value.map((x)=>to_candid_WorkInboxItem_n14(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Note>): Array<_Note> {
    return value.map((x)=>to_candid_Note_n10(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ContentPlan>): Array<_ContentPlan> {
    return value.map((x)=>to_candid_ContentPlan_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
